apiVersion: apps/v1
kind: Deployment

metadata:
  name: leave-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: leave-app

  template:
    metadata:
      labels:
        app: leave-app

    spec:
      containers:
      - name: leave-app
        image: dharshana20/leave-app:v2
        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: DEBUG
          value: "True"