apiVersion: v1
kind: Service
metadata:
  name: leave-service
spec:
  type: NodePort
  selector:
    app: leave-app
  sessionAffinity: ClientIP   
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007