# Generated by Django 5.2.13 on 2026-05-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='created_at',
            new_name='applied_on',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='employee',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager_comment',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
